open! Core

(** Represents the type of a syscall argument *)
module Arg_type = struct
  type t =
    | File_descriptor
    | Path
    | Pointer
    | Int
    | Unsigned_int
    | Size
    | Offset
    | Flags
    | String
    | Struct
    | Sockaddr
    | Buffer
    | Pid
    | Signal
    | Mode
    | Other of string
  [@@deriving sexp_of, equal, compare]

  let is_file_descriptor = function
    | File_descriptor -> true
    | _ -> false
  ;;
end

module Arg_spec = struct
  type t =
    { name : string
    ; arg_type : Arg_type.t
    }
  [@@deriving sexp_of, fields ~getters]
end

module Return_type = struct
  type t =
    | File_descriptor
    | Int
    | Ssize
    | Pointer
    | Void
    | Pid
    | Off
  [@@deriving sexp_of, equal]

  let is_file_descriptor = function
    | File_descriptor -> true
    | _ -> false
  ;;
end

module Signature = struct
  type t =
    { c_signature : string
    ; args : Arg_spec.t list
    ; return_type : Return_type.t
    }
  [@@deriving sexp_of, fields ~getters]
end

module Syscall_info = struct
  type t =
    { name : string
    ; signatures : Signature.t list
    ; brief : string
    ; man_section : int
    }
  [@@deriving sexp_of, fields ~getters]

  let best_signature t ~arg_count =
    match
      List.find t.signatures ~f:(fun sig_ ->
        List.length (Signature.args sig_) = arg_count)
    with
    | Some s -> s
    | None ->
      (* Fall back to the signature with the most args (most detailed) *)
      List.max_elt t.signatures ~compare:(fun a b ->
        Int.compare (List.length (Signature.args a)) (List.length (Signature.args b)))
      |> Option.value ~default:(List.hd_exn t.signatures)
  ;;
end

(** Auto-generated by schema_generator. Do not edit by hand. To regenerate: run the
    schema_generator binary and replace the known_syscalls definition in syscall_schema.ml
    with the output. *)

let known_syscalls =
  let signature ~c_signature ~args ~return_type =
    { Signature.c_signature; args; return_type }
  in
  let entry name ~c_signature ~args ~return_type ~brief ~man_section =
    ( name
    , { Syscall_info.name
      ; signatures = [ signature ~c_signature ~args ~return_type ]
      ; brief
      ; man_section
      } )
  in
  let entry_multi name ~signatures ~brief ~man_section =
    name, { Syscall_info.name; signatures; brief; man_section }
  in
  let fd = Arg_type.File_descriptor in
  let path = Arg_type.Path in
  let ptr = Arg_type.Pointer in
  let int_ = Arg_type.Int in
  let uint = Arg_type.Unsigned_int in
  let size = Arg_type.Size in
  let off = Arg_type.Offset in
  let flags = Arg_type.Flags in
  let _str = Arg_type.String in
  let buf = Arg_type.Buffer in
  let pid = Arg_type.Pid in
  let sig_ = Arg_type.Signal in
  let mode = Arg_type.Mode in
  let struct_ = Arg_type.Struct in
  let sockaddr = Arg_type.Sockaddr in
  let a name arg_type = { Arg_spec.name; arg_type } in
  String.Map.of_alist_exn
    [ entry
        "read"
        ~c_signature:"ssize_t read(int fd , void * buf , size_t count )"
        ~args:[ a "fd" fd; a "buf" buf; a "count" size ]
        ~return_type:Ssize
        ~brief:"Read from a file descriptor"
        ~man_section:2
    ; entry
        "write"
        ~c_signature:"ssize_t write(int fd , const void * buf , size_t count )"
        ~args:[ a "fd" fd; a "buf" buf; a "count" size ]
        ~return_type:Ssize
        ~brief:"Write to a file descriptor"
        ~man_section:2
    ; entry_multi
        "open"
        ~signatures:
          [ signature
              ~c_signature:"int open(const char * pathname , int flags )"
              ~args:[ a "pathname" path; a "flags" flags ]
              ~return_type:File_descriptor
          ; signature
              ~c_signature:"int open(const char * pathname , int flags , mode_t mode )"
              ~args:[ a "pathname" path; a "flags" flags; a "mode" mode ]
              ~return_type:File_descriptor
          ]
        ~brief:"Open and possibly create a file"
        ~man_section:2
    ; entry_multi
        "openat"
        ~signatures:
          [ signature
              ~c_signature:"int openat(int dirfd , const char * pathname , int flags )"
              ~args:[ a "dirfd" fd; a "pathname" path; a "flags" flags ]
              ~return_type:File_descriptor
          ; signature
              ~c_signature:
                "int openat(int dirfd , const char * pathname , int flags , mode_t mode )"
              ~args:[ a "dirfd" fd; a "pathname" path; a "flags" flags; a "mode" mode ]
              ~return_type:File_descriptor
          ]
        ~brief:"Open and possibly create a file"
        ~man_section:2
    ; entry
        "close"
        ~c_signature:"int close(int fd )"
        ~args:[ a "fd" fd ]
        ~return_type:Int
        ~brief:"Close a file descriptor"
        ~man_section:2
    ; entry
        "lseek"
        ~c_signature:"off_t lseek(int fd , off_t offset , int whence )"
        ~args:[ a "fd" fd; a "offset" off; a "whence" flags ]
        ~return_type:Off
        ~brief:"Reposition read/write file offset"
        ~man_section:2
    ; entry
        "pread64"
        ~c_signature:"ssize_t pread(int fd , void * buf , size_t count , off_t offset )"
        ~args:[ a "fd" fd; a "buf" buf; a "count" size; a "offset" off ]
        ~return_type:Ssize
        ~brief:"Read from or write to a file descriptor at a given offset"
        ~man_section:2
    ; entry
        "pwrite64"
        ~c_signature:
          "ssize_t pwrite(int fd , const void * buf , size_t count , off_t offset )"
        ~args:[ a "fd" fd; a "buf" buf; a "count" size; a "offset" off ]
        ~return_type:Ssize
        ~brief:"Read from or write to a file descriptor at a given offset"
        ~man_section:2
    ; entry
        "readv"
        ~c_signature:"ssize_t readv(int fd , const struct iovec * iov , int iovcnt )"
        ~args:[ a "fd" fd; a "iov" struct_; a "iovcnt" int_ ]
        ~return_type:Ssize
        ~brief:"Read or write data into multiple buffers"
        ~man_section:2
    ; entry
        "writev"
        ~c_signature:"ssize_t writev(int fd , const struct iovec * iov , int iovcnt )"
        ~args:[ a "fd" fd; a "iov" struct_; a "iovcnt" int_ ]
        ~return_type:Ssize
        ~brief:"Read or write data into multiple buffers"
        ~man_section:2
    ; entry
        "dup"
        ~c_signature:"int dup(int oldfd )"
        ~args:[ a "oldfd" fd ]
        ~return_type:File_descriptor
        ~brief:"Duplicate a file descriptor"
        ~man_section:2
    ; entry
        "dup2"
        ~c_signature:"int dup2(int oldfd , int newfd )"
        ~args:[ a "oldfd" fd; a "newfd" fd ]
        ~return_type:File_descriptor
        ~brief:"Duplicate a file descriptor"
        ~man_section:2
    ; entry
        "dup3"
        ~c_signature:"int dup3(int oldfd , int newfd , int flags )"
        ~args:[ a "oldfd" fd; a "newfd" fd; a "flags" flags ]
        ~return_type:File_descriptor
        ~brief:"Duplicate a file descriptor"
        ~man_section:2
    ; entry
        "stat"
        ~c_signature:"int stat(const char * pathname , struct stat * statbuf )"
        ~args:[ a "pathname" path; a "statbuf" struct_ ]
        ~return_type:Int
        ~brief:"Get file status"
        ~man_section:2
    ; entry
        "fstat"
        ~c_signature:"int fstat(int fd , struct stat * statbuf )"
        ~args:[ a "fd" fd; a "statbuf" struct_ ]
        ~return_type:Int
        ~brief:"Get file status"
        ~man_section:2
    ; entry
        "lstat"
        ~c_signature:"int lstat(const char * pathname , struct stat * statbuf )"
        ~args:[ a "pathname" path; a "statbuf" struct_ ]
        ~return_type:Int
        ~brief:"Get file status"
        ~man_section:2
    ; entry
        "access"
        ~c_signature:"int access(const char * pathname , int mode )"
        ~args:[ a "pathname" path; a "mode" int_ ]
        ~return_type:Int
        ~brief:"Check user's permissions for a file"
        ~man_section:2
    ; entry
        "faccessat"
        ~c_signature:
          "int faccessat(int dirfd , const char * pathname , int mode , int flags )"
        ~args:[ a "dirfd" fd; a "pathname" path; a "mode" int_; a "flags" flags ]
        ~return_type:Int
        ~brief:"Check user's permissions for a file"
        ~man_section:2
    ; entry
        "unlink"
        ~c_signature:"int unlink(const char * pathname )"
        ~args:[ a "pathname" path ]
        ~return_type:Int
        ~brief:"Delete a name and possibly the file it refers to"
        ~man_section:2
    ; entry
        "unlinkat"
        ~c_signature:"int unlinkat(int dirfd , const char * pathname , int flags )"
        ~args:[ a "dirfd" fd; a "pathname" path; a "flags" flags ]
        ~return_type:Int
        ~brief:"Delete a name and possibly the file it refers to"
        ~man_section:2
    ; entry
        "rename"
        ~c_signature:"int rename(const char * oldpath , const char * newpath )"
        ~args:[ a "oldpath" path; a "newpath" path ]
        ~return_type:Int
        ~brief:"Change the name or location of a file"
        ~man_section:2
    ; entry
        "renameat"
        ~c_signature:
          "int renameat(int olddirfd , const char * oldpath , int newdirfd , const char \
           * newpath )"
        ~args:[ a "olddirfd" fd; a "oldpath" path; a "newdirfd" fd; a "newpath" path ]
        ~return_type:Int
        ~brief:"Change the name or location of a file"
        ~man_section:2
    ; entry
        "renameat2"
        ~c_signature:
          "int renameat2(int olddirfd , const char * oldpath , int newdirfd , const char \
           * newpath , unsigned int flags )"
        ~args:
          [ a "olddirfd" fd
          ; a "oldpath" path
          ; a "newdirfd" fd
          ; a "newpath" path
          ; a "flags" flags
          ]
        ~return_type:Int
        ~brief:"Change the name or location of a file"
        ~man_section:2
    ; entry
        "mkdir"
        ~c_signature:"int mkdir(const char * pathname , mode_t mode )"
        ~args:[ a "pathname" path; a "mode" mode ]
        ~return_type:Int
        ~brief:"Create a directory"
        ~man_section:2
    ; entry
        "mkdirat"
        ~c_signature:"int mkdirat(int dirfd , const char * pathname , mode_t mode )"
        ~args:[ a "dirfd" fd; a "pathname" path; a "mode" mode ]
        ~return_type:Int
        ~brief:"Create a directory"
        ~man_section:2
    ; entry
        "rmdir"
        ~c_signature:"int rmdir(const char * pathname )"
        ~args:[ a "pathname" path ]
        ~return_type:Int
        ~brief:"Delete a directory"
        ~man_section:2
    ; entry
        "link"
        ~c_signature:"int link(const char * oldpath , const char * newpath )"
        ~args:[ a "oldpath" path; a "newpath" path ]
        ~return_type:Int
        ~brief:"Make a new name for a file"
        ~man_section:2
    ; entry
        "linkat"
        ~c_signature:
          "int linkat(int olddirfd , const char * oldpath , int newdirfd , const char * \
           newpath , int flags )"
        ~args:
          [ a "olddirfd" fd
          ; a "oldpath" path
          ; a "newdirfd" fd
          ; a "newpath" path
          ; a "flags" flags
          ]
        ~return_type:Int
        ~brief:"Make a new name for a file"
        ~man_section:2
    ; entry
        "symlink"
        ~c_signature:"int symlink(const char * target , const char * linkpath )"
        ~args:[ a "target" path; a "linkpath" path ]
        ~return_type:Int
        ~brief:"Make a new name for a file"
        ~man_section:2
    ; entry
        "symlinkat"
        ~c_signature:
          "int symlinkat(const char * target , int newdirfd , const char * linkpath )"
        ~args:[ a "target" path; a "newdirfd" fd; a "linkpath" path ]
        ~return_type:Int
        ~brief:"Make a new name for a file"
        ~man_section:2
    ; entry
        "readlink"
        ~c_signature:
          "ssize_t readlink(const char * pathname , char * buf , size_t bufsiz )"
        ~args:[ a "pathname" path; a "buf" buf; a "bufsiz" size ]
        ~return_type:Ssize
        ~brief:"Read value of a symbolic link"
        ~man_section:2
    ; entry
        "readlinkat"
        ~c_signature:
          "ssize_t readlinkat(int dirfd , const char * pathname , char * buf , size_t \
           bufsiz )"
        ~args:[ a "dirfd" fd; a "pathname" path; a "buf" buf; a "bufsiz" size ]
        ~return_type:Ssize
        ~brief:"Read value of a symbolic link"
        ~man_section:2
    ; entry
        "chmod"
        ~c_signature:"int chmod(const char * pathname , mode_t mode )"
        ~args:[ a "pathname" path; a "mode" mode ]
        ~return_type:Int
        ~brief:"Change permissions of a file"
        ~man_section:2
    ; entry
        "fchmod"
        ~c_signature:"int fchmod(int fd , mode_t mode )"
        ~args:[ a "fd" fd; a "mode" mode ]
        ~return_type:Int
        ~brief:"Change permissions of a file"
        ~man_section:2
    ; entry
        "chown"
        ~c_signature:"int chown(const char * pathname , uid_t owner , gid_t group )"
        ~args:[ a "pathname" path; a "owner" int_; a "group" int_ ]
        ~return_type:Int
        ~brief:"Change ownership of a file"
        ~man_section:2
    ; entry
        "fchown"
        ~c_signature:"int fchown(int fd , uid_t owner , gid_t group )"
        ~args:[ a "fd" fd; a "owner" int_; a "group" int_ ]
        ~return_type:Int
        ~brief:"Change ownership of a file"
        ~man_section:2
    ; entry
        "truncate"
        ~c_signature:"int truncate(const char * path , off_t length )"
        ~args:[ a "path" path; a "length" off ]
        ~return_type:Int
        ~brief:"Truncate a file to a specified length"
        ~man_section:2
    ; entry
        "ftruncate"
        ~c_signature:"int ftruncate(int fd , off_t length )"
        ~args:[ a "fd" fd; a "length" off ]
        ~return_type:Int
        ~brief:"Truncate a file to a specified length"
        ~man_section:2
    ; entry
        "getcwd"
        ~c_signature:"char *getcwd(char * buf , size_t size )"
        ~args:[ a "buf" buf; a "size" size ]
        ~return_type:Pointer
        ~brief:"Get current working directory"
        ~man_section:3
    ; entry
        "chdir"
        ~c_signature:"int chdir(const char * path )"
        ~args:[ a "path" path ]
        ~return_type:Int
        ~brief:"Change working directory"
        ~man_section:2
    ; entry
        "fchdir"
        ~c_signature:"int fchdir(int fd )"
        ~args:[ a "fd" fd ]
        ~return_type:Int
        ~brief:"Change working directory"
        ~man_section:2
    ; entry
        "mmap"
        ~c_signature:
          "void *mmap(void * addr , size_t length , int prot , int flags , int fd , \
           off_t offset )"
        ~args:
          [ a "addr" ptr
          ; a "length" size
          ; a "prot" flags
          ; a "flags" flags
          ; a "fd" fd
          ; a "offset" off
          ]
        ~return_type:Pointer
        ~brief:"Map or unmap files or devices into memory"
        ~man_section:2
    ; entry
        "munmap"
        ~c_signature:"int munmap(void * addr , size_t length )"
        ~args:[ a "addr" ptr; a "length" size ]
        ~return_type:Int
        ~brief:"Map or unmap files or devices into memory"
        ~man_section:2
    ; entry
        "mprotect"
        ~c_signature:"int mprotect(void * addr , size_t len , int prot )"
        ~args:[ a "addr" ptr; a "len" size; a "prot" flags ]
        ~return_type:Int
        ~brief:"Set protection on a region of memory"
        ~man_section:2
    ; entry
        "brk"
        ~c_signature:"int brk(void * addr )"
        ~args:[ a "addr" ptr ]
        ~return_type:Int
        ~brief:"Change data segment size"
        ~man_section:2
    ; entry
        "execve"
        ~c_signature:
          "int execve(const char * filename , char *const argv [], char *const envp [])"
        ~args:[ a "filename" path; a "argv" ptr; a "envp" ptr ]
        ~return_type:Int
        ~brief:"Execute program"
        ~man_section:2
    ; entry
        "fork"
        ~c_signature:"pid_t fork(void)"
        ~args:[]
        ~return_type:Pid
        ~brief:"Create a child process"
        ~man_section:2
    ; entry
        "vfork"
        ~c_signature:"pid_t vfork(void)"
        ~args:[]
        ~return_type:Pid
        ~brief:"Create a child process and block parent"
        ~man_section:2
    ; entry
        "clone"
        ~c_signature:
          "long clone(unsigned long flags, void *child_stack, int *ptid, int *ctid, \
           unsigned long newtls)"
        ~args:
          [ a "flags" flags
          ; a "child_stack" ptr
          ; a "ptid" ptr
          ; a "ctid" ptr
          ; a "newtls" uint
          ]
        ~return_type:Pid
        ~brief:"Create a child process"
        ~man_section:2
    ; entry
        "exit_group"
        ~c_signature:"void exit_group(int status )"
        ~args:[ a "status" int_ ]
        ~return_type:Void
        ~brief:"Exit all threads in a process"
        ~man_section:2
    ; entry
        "wait4"
        ~c_signature:
          "pid_t wait4(pid_t pid , int * wstatus , int options , struct rusage * rusage )"
        ~args:[ a "pid" pid; a "wstatus" ptr; a "options" flags; a "rusage" struct_ ]
        ~return_type:Pid
        ~brief:"Wait for process to change state, BSD style"
        ~man_section:2
    ; entry
        "waitid"
        ~c_signature:
          "int waitid(idtype_t idtype , id_t id , siginfo_t * infop , int options )"
        ~args:[ a "idtype" int_; a "id" int_; a "infop" ptr; a "options" flags ]
        ~return_type:Int
        ~brief:"Wait for process to change state"
        ~man_section:2
    ; entry
        "kill"
        ~c_signature:"int kill(pid_t pid , int sig )"
        ~args:[ a "pid" pid; a "sig" sig_ ]
        ~return_type:Int
        ~brief:"Send signal to a process"
        ~man_section:2
    ; entry
        "getpid"
        ~c_signature:"pid_t getpid(void)"
        ~args:[]
        ~return_type:Pid
        ~brief:"Get process identification"
        ~man_section:2
    ; entry
        "getppid"
        ~c_signature:"pid_t getppid(void)"
        ~args:[]
        ~return_type:Pid
        ~brief:"Get process identification"
        ~man_section:2
    ; entry
        "getuid"
        ~c_signature:"uid_t getuid(void)"
        ~args:[]
        ~return_type:Int
        ~brief:"Get user identity"
        ~man_section:2
    ; entry
        "getgid"
        ~c_signature:"gid_t getgid(void)"
        ~args:[]
        ~return_type:Int
        ~brief:"Get group identity"
        ~man_section:2
    ; entry
        "geteuid"
        ~c_signature:"uid_t geteuid(void)"
        ~args:[]
        ~return_type:Int
        ~brief:"Get user identity"
        ~man_section:2
    ; entry
        "getegid"
        ~c_signature:"gid_t getegid(void)"
        ~args:[]
        ~return_type:Int
        ~brief:"Get group identity"
        ~man_section:2
    ; entry
        "socket"
        ~c_signature:"int socket(int domain , int type , int protocol )"
        ~args:[ a "domain" int_; a "type" int_; a "protocol" flags ]
        ~return_type:File_descriptor
        ~brief:"Create an endpoint for communication"
        ~man_section:2
    ; entry
        "connect"
        ~c_signature:
          "int connect(int sockfd , const struct sockaddr * addr , socklen_t addrlen )"
        ~args:[ a "sockfd" fd; a "addr" sockaddr; a "addrlen" size ]
        ~return_type:Int
        ~brief:"Initiate a connection on a socket"
        ~man_section:2
    ; entry
        "accept"
        ~c_signature:
          "int accept(int sockfd , struct sockaddr * addr , socklen_t * addrlen )"
        ~args:[ a "sockfd" fd; a "addr" sockaddr; a "addrlen" size ]
        ~return_type:File_descriptor
        ~brief:"Accept a connection on a socket"
        ~man_section:2
    ; entry
        "accept4"
        ~c_signature:
          "int accept4(int sockfd , struct sockaddr * addr , socklen_t * addrlen , int \
           flags )"
        ~args:[ a "sockfd" fd; a "addr" sockaddr; a "addrlen" size; a "flags" flags ]
        ~return_type:File_descriptor
        ~brief:"Accept a connection on a socket"
        ~man_section:2
    ; entry
        "bind"
        ~c_signature:
          "int bind(int sockfd , const struct sockaddr * addr , socklen_t addrlen )"
        ~args:[ a "sockfd" fd; a "addr" sockaddr; a "addrlen" size ]
        ~return_type:Int
        ~brief:"Bind a name to a socket"
        ~man_section:2
    ; entry
        "listen"
        ~c_signature:"int listen(int sockfd , int backlog )"
        ~args:[ a "sockfd" fd; a "backlog" int_ ]
        ~return_type:Int
        ~brief:"Listen for connections on a socket"
        ~man_section:2
    ; entry
        "sendto"
        ~c_signature:
          "ssize_t sendto(int sockfd , const void * buf , size_t len , int flags , const \
           struct sockaddr * dest_addr , socklen_t addrlen )"
        ~args:
          [ a "sockfd" fd
          ; a "buf" buf
          ; a "len" size
          ; a "flags" flags
          ; a "dest_addr" sockaddr
          ; a "addrlen" size
          ]
        ~return_type:Ssize
        ~brief:"Send a message on a socket"
        ~man_section:2
    ; entry
        "recvfrom"
        ~c_signature:
          "ssize_t recvfrom(int sockfd , void * buf , size_t len , int flags , struct \
           sockaddr * src_addr , socklen_t * addrlen )"
        ~args:
          [ a "sockfd" fd
          ; a "buf" buf
          ; a "len" size
          ; a "flags" flags
          ; a "src_addr" sockaddr
          ; a "addrlen" size
          ]
        ~return_type:Ssize
        ~brief:"Receive a message from a socket"
        ~man_section:2
    ; entry
        "sendmsg"
        ~c_signature:
          "ssize_t sendmsg(int sockfd , const struct msghdr * msg , int flags )"
        ~args:[ a "sockfd" fd; a "msg" struct_; a "flags" flags ]
        ~return_type:Ssize
        ~brief:"Send a message on a socket"
        ~man_section:2
    ; entry
        "recvmsg"
        ~c_signature:"ssize_t recvmsg(int sockfd , struct msghdr * msg , int flags )"
        ~args:[ a "sockfd" fd; a "msg" struct_; a "flags" flags ]
        ~return_type:Ssize
        ~brief:"Receive a message from a socket"
        ~man_section:2
    ; entry
        "shutdown"
        ~c_signature:"int shutdown(int sockfd , int how )"
        ~args:[ a "sockfd" fd; a "how" int_ ]
        ~return_type:Int
        ~brief:"Shut down part of a full-duplex connection"
        ~man_section:2
    ; entry
        "setsockopt"
        ~c_signature:
          "int setsockopt(int sockfd , int level , int optname , const void * optval , \
           socklen_t optlen )"
        ~args:
          [ a "sockfd" fd
          ; a "level" int_
          ; a "optname" int_
          ; a "optval" ptr
          ; a "optlen" size
          ]
        ~return_type:Int
        ~brief:"Get and set options on sockets"
        ~man_section:2
    ; entry
        "getsockopt"
        ~c_signature:
          "int getsockopt(int sockfd , int level , int optname , void * optval , \
           socklen_t * optlen )"
        ~args:
          [ a "sockfd" fd
          ; a "level" int_
          ; a "optname" int_
          ; a "optval" ptr
          ; a "optlen" size
          ]
        ~return_type:Int
        ~brief:"Get and set options on sockets"
        ~man_section:2
    ; entry
        "getsockname"
        ~c_signature:
          "int getsockname(int sockfd , struct sockaddr * addr , socklen_t * addrlen )"
        ~args:[ a "sockfd" fd; a "addr" sockaddr; a "addrlen" size ]
        ~return_type:Int
        ~brief:"Get socket name"
        ~man_section:2
    ; entry
        "getpeername"
        ~c_signature:
          "int getpeername(int sockfd , struct sockaddr * addr , socklen_t * addrlen )"
        ~args:[ a "sockfd" fd; a "addr" sockaddr; a "addrlen" size ]
        ~return_type:Int
        ~brief:"Get name of connected peer socket"
        ~man_section:2
    ; entry
        "socketpair"
        ~c_signature:"int socketpair(int domain , int type , int protocol , int sv [2])"
        ~args:[ a "domain" int_; a "type" int_; a "protocol" flags; a "sv" int_ ]
        ~return_type:File_descriptor
        ~brief:"Create a pair of connected sockets"
        ~man_section:2
    ; entry
        "select"
        ~c_signature:
          "int select(int nfds , fd_set * readfds , fd_set * writefds , fd_set * \
           exceptfds , struct timeval * timeout )"
        ~args:
          [ a "nfds" fd
          ; a "readfds" ptr
          ; a "writefds" ptr
          ; a "exceptfds" ptr
          ; a "timeout" struct_
          ]
        ~return_type:Int
        ~brief:"Synchronous I/O multiplexing"
        ~man_section:2
    ; entry
        "poll"
        ~c_signature:"int poll(struct pollfd * fds , nfds_t nfds , int timeout )"
        ~args:[ a "fds" struct_; a "nfds" (Arg_type.Other "nfds_t"); a "timeout" int_ ]
        ~return_type:Int
        ~brief:"Wait for some event on a file descriptor"
        ~man_section:2
    ; entry
        "ppoll"
        ~c_signature:
          "int ppoll(struct pollfd * fds , nfds_t nfds , const struct timespec * tmo_p , \
           const sigset_t * sigmask )"
        ~args:
          [ a "fds" struct_
          ; a "nfds" (Arg_type.Other "nfds_t")
          ; a "tmo_p" struct_
          ; a "sigmask" ptr
          ]
        ~return_type:Int
        ~brief:"Wait for some event on a file descriptor"
        ~man_section:2
    ; entry
        "epoll_create"
        ~c_signature:"int epoll_create(int size )"
        ~args:[ a "size" int_ ]
        ~return_type:File_descriptor
        ~brief:"Open an epoll file descriptor"
        ~man_section:2
    ; entry
        "epoll_create1"
        ~c_signature:"int epoll_create1(int flags )"
        ~args:[ a "flags" flags ]
        ~return_type:File_descriptor
        ~brief:"Open an epoll file descriptor"
        ~man_section:2
    ; entry
        "epoll_ctl"
        ~c_signature:
          "int epoll_ctl(int epfd , int op , int fd , struct epoll_event * event )"
        ~args:[ a "epfd" fd; a "op" int_; a "fd" fd; a "event" struct_ ]
        ~return_type:Int
        ~brief:"Control interface for an epoll file descriptor"
        ~man_section:2
    ; entry
        "epoll_wait"
        ~c_signature:
          "int epoll_wait(int epfd , struct epoll_event * events , int maxevents , int \
           timeout )"
        ~args:[ a "epfd" fd; a "events" struct_; a "maxevents" int_; a "timeout" int_ ]
        ~return_type:Int
        ~brief:"Wait for an I/O event on an epoll file descriptor"
        ~man_section:2
    ; entry
        "epoll_pwait"
        ~c_signature:
          "int epoll_pwait(int epfd , struct epoll_event * events , int maxevents , int \
           timeout , const sigset_t * sigmask )"
        ~args:
          [ a "epfd" fd
          ; a "events" struct_
          ; a "maxevents" int_
          ; a "timeout" int_
          ; a "sigmask" ptr
          ]
        ~return_type:Int
        ~brief:"Wait for an I/O event on an epoll file descriptor"
        ~man_section:2
    ; entry
        "pipe"
        ~c_signature:"int pipe(int pipefd [2])"
        ~args:[ a "pipefd" fd ]
        ~return_type:Int
        ~brief:"Create pipe"
        ~man_section:2
    ; entry
        "pipe2"
        ~c_signature:"int pipe2(int pipefd [2], int flags )"
        ~args:[ a "pipefd" fd; a "flags" flags ]
        ~return_type:Int
        ~brief:"Create pipe"
        ~man_section:2
    ; entry
        "ioctl"
        ~c_signature:"int ioctl(int fd , unsigned long request , ...)"
        ~args:[ a "fd" fd; a "request" uint ]
        ~return_type:Int
        ~brief:"Control device"
        ~man_section:2
    ; entry
        "fcntl"
        ~c_signature:"int fcntl(int fd , int cmd , ... /* arg */ )"
        ~args:[ a "fd" fd; a "cmd" int_ ]
        ~return_type:Int
        ~brief:"Manipulate file descriptor"
        ~man_section:2
    ; entry
        "rt_sigaction"
        ~c_signature:
          "int sigaction(int signum , const struct sigaction * act , struct sigaction * \
           oldact )"
        ~args:[ a "signum" sig_; a "act" struct_; a "oldact" struct_ ]
        ~return_type:Int
        ~brief:"Examine and change a signal action"
        ~man_section:2
    ; entry_multi
        "rt_sigprocmask"
        ~signatures:
          [ signature
              ~c_signature:
                "int sigprocmask(int how , const sigset_t * set , sigset_t * oldset )"
              ~args:[ a "how" int_; a "set" ptr; a "oldset" ptr ]
              ~return_type:Int
          ; signature
              ~c_signature:
                "int rt_sigprocmask(int how , const kernel_sigset_t * set , \
                 kernel_sigset_t * oldset , size_t sigsetsize )"
              ~args:[ a "how" int_; a "set" ptr; a "oldset" ptr; a "sigsetsize" size ]
              ~return_type:Int
          ; signature
              ~c_signature:
                "int sigprocmask(int how , const old_kernel_sigset_t * set , \
                 old_kernel_sigset_t * oldset )"
              ~args:[ a "how" int_; a "set" ptr; a "oldset" ptr ]
              ~return_type:Int
          ]
        ~brief:"Examine and change blocked signals"
        ~man_section:2
    ; entry
        "rt_sigreturn"
        ~c_signature:"int sigreturn(...)"
        ~args:[]
        ~return_type:Int
        ~brief:"Return from signal handler and cleanup stack frame"
        ~man_section:2
    ; entry
        "sigaltstack"
        ~c_signature:"int sigaltstack(const stack_t * ss , stack_t * old_ss )"
        ~args:[ a "ss" ptr; a "old_ss" ptr ]
        ~return_type:Int
        ~brief:"Set and/or get signal stack context"
        ~man_section:2
    ; entry_multi
        "arch_prctl"
        ~signatures:
          [ signature
              ~c_signature:"int arch_prctl(int code , unsigned long addr )"
              ~args:[ a "code" int_; a "addr" uint ]
              ~return_type:Int
          ; signature
              ~c_signature:"int arch_prctl(int code , unsigned long * addr )"
              ~args:[ a "code" int_; a "addr" ptr ]
              ~return_type:Int
          ]
        ~brief:"Set architecture-specific thread state"
        ~man_section:2
    ; entry
        "set_tid_address"
        ~c_signature:"long set_tid_address(int * tidptr )"
        ~args:[ a "tidptr" ptr ]
        ~return_type:Int
        ~brief:"Set pointer to thread ID"
        ~man_section:2
    ; entry
        "set_robust_list"
        ~c_signature:"long set_robust_list(struct robust_list_head * head , size_t len )"
        ~args:[ a "head" struct_; a "len" size ]
        ~return_type:Int
        ~brief:"Get/set list of robust futexes"
        ~man_section:2
    ; entry
        "futex"
        ~c_signature:
          "int futex(int * uaddr , int futex_op , int val , const struct timespec * \
           timeout , /* or: uint32_t val2 */ int * uaddr2 , int val3 )"
        ~args:
          [ a "uaddr" ptr
          ; a "futex_op" int_
          ; a "val" int_
          ; a "timeout" struct_
          ; a "uaddr2" ptr
          ; a "val3" int_
          ]
        ~return_type:Int
        ~brief:"Fast user-space locking"
        ~man_section:2
    ; entry
        "nanosleep"
        ~c_signature:"int nanosleep(const struct timespec * req , struct timespec * rem )"
        ~args:[ a "req" struct_; a "rem" struct_ ]
        ~return_type:Int
        ~brief:"High-resolution sleep"
        ~man_section:2
    ; entry
        "clock_gettime"
        ~c_signature:"int clock_gettime(clockid_t clk_id , struct timespec * tp )"
        ~args:[ a "clk_id" int_; a "tp" struct_ ]
        ~return_type:Int
        ~brief:"Clock and time functions"
        ~man_section:2
    ; entry
        "clock_getres"
        ~c_signature:"int clock_getres(clockid_t clk_id , struct timespec * res )"
        ~args:[ a "clk_id" int_; a "res" struct_ ]
        ~return_type:Int
        ~brief:"Clock and time functions"
        ~man_section:2
    ; entry
        "clock_nanosleep"
        ~c_signature:
          "int clock_nanosleep(clockid_t clock_id , int flags , const struct timespec * \
           request , struct timespec * remain )"
        ~args:
          [ a "clock_id" int_; a "flags" flags; a "request" struct_; a "remain" struct_ ]
        ~return_type:Int
        ~brief:"High-resolution sleep with specifiable clock"
        ~man_section:2
    ; entry
        "gettimeofday"
        ~c_signature:"int gettimeofday(struct timeval * tv , struct timezone * tz )"
        ~args:[ a "tv" struct_; a "tz" struct_ ]
        ~return_type:Int
        ~brief:"Get / set time"
        ~man_section:2
    ; entry
        "getrlimit"
        ~c_signature:"int getrlimit(int resource , struct rlimit * rlim )"
        ~args:[ a "resource" int_; a "rlim" struct_ ]
        ~return_type:Int
        ~brief:"Get/set resource limits"
        ~man_section:2
    ; entry
        "prlimit64"
        ~c_signature:
          "int prlimit(pid_t pid , int resource , const struct rlimit * new_limit , \
           struct rlimit * old_limit )"
        ~args:
          [ a "pid" pid; a "resource" int_; a "new_limit" struct_; a "old_limit" struct_ ]
        ~return_type:Int
        ~brief:"Get/set resource limits"
        ~man_section:2
    ; entry
        "getdents64"
        ~c_signature:
          "int getdents64(unsigned int fd , struct linux_dirent64 * dirp , unsigned int \
           count )"
        ~args:[ a "fd" fd; a "dirp" struct_; a "count" size ]
        ~return_type:Int
        ~brief:"Get directory entries"
        ~man_section:2
    ; entry
        "statfs"
        ~c_signature:"int statfs(const char * path , struct statfs * buf )"
        ~args:[ a "path" path; a "buf" struct_ ]
        ~return_type:Int
        ~brief:"Get filesystem statistics"
        ~man_section:2
    ; entry
        "fstatfs"
        ~c_signature:"int fstatfs(int fd , struct statfs * buf )"
        ~args:[ a "fd" fd; a "buf" struct_ ]
        ~return_type:Int
        ~brief:"Get filesystem statistics"
        ~man_section:2
    ; entry
        "statx"
        ~c_signature:
          "int statx(int dirfd , const char * pathname , int flags , unsigned int mask , \
           struct statx * statxbuf )"
        ~args:
          [ a "dirfd" fd
          ; a "pathname" path
          ; a "flags" flags
          ; a "mask" uint
          ; a "statxbuf" struct_
          ]
        ~return_type:Int
        ~brief:"Get file status (extended)"
        ~man_section:2
    ; entry
        "sendfile"
        ~c_signature:
          "ssize_t sendfile(int out_fd , int in_fd , off_t * offset , size_t count )"
        ~args:[ a "out_fd" fd; a "in_fd" fd; a "offset" off; a "count" size ]
        ~return_type:Ssize
        ~brief:"Transfer data between file descriptors"
        ~man_section:2
    ; entry
        "eventfd2"
        ~c_signature:"int eventfd(unsigned int initval , int flags )"
        ~args:[ a "initval" uint; a "flags" flags ]
        ~return_type:File_descriptor
        ~brief:"Create a file descriptor for event notification"
        ~man_section:2
    ; entry
        "timerfd_create"
        ~c_signature:"int timerfd_create(int clockid , int flags )"
        ~args:[ a "clockid" int_; a "flags" flags ]
        ~return_type:File_descriptor
        ~brief:"Timers that notify via file descriptors"
        ~man_section:2
    ; entry
        "timerfd_settime"
        ~c_signature:
          "int timerfd_settime(int fd , int flags , const struct itimerspec * new_value \
           , struct itimerspec * old_value )"
        ~args:[ a "fd" fd; a "flags" flags; a "new_value" struct_; a "old_value" struct_ ]
        ~return_type:Int
        ~brief:"Timers that notify via file descriptors"
        ~man_section:2
    ; entry
        "timerfd_gettime"
        ~c_signature:"int timerfd_gettime(int fd , struct itimerspec * curr_value )"
        ~args:[ a "fd" fd; a "curr_value" struct_ ]
        ~return_type:Int
        ~brief:"Timers that notify via file descriptors"
        ~man_section:2
    ; entry
        "signalfd4"
        ~c_signature:"int signalfd(int fd , const sigset_t * mask , int flags )"
        ~args:[ a "fd" fd; a "mask" ptr; a "flags" flags ]
        ~return_type:File_descriptor
        ~brief:"Create a file descriptor for accepting signals"
        ~man_section:2
    ; entry
        "inotify_init1"
        ~c_signature:"int inotify_init1(int flags )"
        ~args:[ a "flags" flags ]
        ~return_type:File_descriptor
        ~brief:"Initialize an inotify instance"
        ~man_section:2
    ; entry
        "inotify_add_watch"
        ~c_signature:
          "int inotify_add_watch(int fd , const char * pathname , uint32_t mask )"
        ~args:[ a "fd" fd; a "pathname" path; a "mask" int_ ]
        ~return_type:Int
        ~brief:"Add a watch to an initialized inotify instance"
        ~man_section:2
    ; entry
        "inotify_rm_watch"
        ~c_signature:"int inotify_rm_watch(int fd , int wd )"
        ~args:[ a "fd" fd; a "wd" int_ ]
        ~return_type:Int
        ~brief:"Remove an existing watch from an inotify instance"
        ~man_section:2
    ; entry
        "prctl"
        ~c_signature:
          "int prctl(int option , unsigned long arg2 , unsigned long arg3 , unsigned \
           long arg4 , unsigned long arg5 )"
        ~args:
          [ a "option" int_; a "arg2" uint; a "arg3" uint; a "arg4" uint; a "arg5" uint ]
        ~return_type:Int
        ~brief:"Operations on a process"
        ~man_section:2
    ; entry
        "sysinfo"
        ~c_signature:"int sysinfo(struct sysinfo * info )"
        ~args:[ a "info" struct_ ]
        ~return_type:Int
        ~brief:"Return system information"
        ~man_section:2
    ; entry
        "uname"
        ~c_signature:"int uname(struct utsname * buf )"
        ~args:[ a "buf" struct_ ]
        ~return_type:Int
        ~brief:"Get name and information about current kernel"
        ~man_section:2
    ; entry
        "getrandom"
        ~c_signature:"ssize_t getrandom(void *buf , size_t buflen , unsigned int flags )"
        ~args:[ a "buf" ptr; a "buflen" size; a "flags" flags ]
        ~return_type:Ssize
        ~brief:"Obtain a series of random bytes"
        ~man_section:2
    ]
;;

(** Syscall families for filtering, corresponding to strace trace groups *)
module Family = struct
  type t =
    | All
    | Desc
    | File
    | Memory
    | Network
    | Process
    | Signal
    | Ipc
  [@@deriving sexp_of, equal, compare, enumerate]

  let to_display_string = function
    | All -> "all"
    | Desc -> "%desc"
    | File -> "%file"
    | Memory -> "%memory"
    | Network -> "%net"
    | Process -> "%process"
    | Signal -> "%signal"
    | Ipc -> "%ipc"
  ;;

  (** Returns true if the given syscall name belongs to this family. This is an
      approximation; strace uses the kernel's classification internally. *)
  let includes t ~syscall_name =
    match t with
    | All -> true
    | Desc ->
      List.mem
        ~equal:String.equal
        [ "read"
        ; "write"
        ; "open"
        ; "openat"
        ; "close"
        ; "lseek"
        ; "pread64"
        ; "pwrite64"
        ; "readv"
        ; "writev"
        ; "dup"
        ; "dup2"
        ; "dup3"
        ; "fstat"
        ; "newfstatat"
        ; "fcntl"
        ; "ioctl"
        ; "ftruncate"
        ; "fchmod"
        ; "fchown"
        ; "fchdir"
        ; "fstatfs"
        ; "getdents64"
        ; "epoll_create"
        ; "epoll_create1"
        ; "epoll_ctl"
        ; "epoll_wait"
        ; "epoll_pwait"
        ; "select"
        ; "poll"
        ; "ppoll"
        ; "pipe"
        ; "pipe2"
        ; "sendfile"
        ; "socket"
        ; "connect"
        ; "accept"
        ; "accept4"
        ; "bind"
        ; "listen"
        ; "sendto"
        ; "recvfrom"
        ; "sendmsg"
        ; "recvmsg"
        ; "shutdown"
        ; "setsockopt"
        ; "getsockopt"
        ; "getsockname"
        ; "getpeername"
        ; "socketpair"
        ; "eventfd2"
        ; "timerfd_create"
        ; "timerfd_settime"
        ; "timerfd_gettime"
        ; "signalfd4"
        ; "inotify_init1"
        ; "inotify_add_watch"
        ; "inotify_rm_watch"
        ]
        syscall_name
    | File ->
      List.mem
        ~equal:String.equal
        [ "open"
        ; "openat"
        ; "stat"
        ; "lstat"
        ; "newfstatat"
        ; "access"
        ; "faccessat"
        ; "unlink"
        ; "unlinkat"
        ; "rename"
        ; "renameat"
        ; "renameat2"
        ; "mkdir"
        ; "mkdirat"
        ; "rmdir"
        ; "link"
        ; "linkat"
        ; "symlink"
        ; "symlinkat"
        ; "readlink"
        ; "readlinkat"
        ; "chmod"
        ; "fchmod"
        ; "chown"
        ; "fchown"
        ; "truncate"
        ; "ftruncate"
        ; "getcwd"
        ; "chdir"
        ; "fchdir"
        ; "statfs"
        ; "fstatfs"
        ; "statx"
        ]
        syscall_name
    | Memory ->
      List.mem ~equal:String.equal [ "mmap"; "munmap"; "mprotect"; "brk" ] syscall_name
    | Network ->
      List.mem
        ~equal:String.equal
        [ "socket"
        ; "connect"
        ; "accept"
        ; "accept4"
        ; "bind"
        ; "listen"
        ; "sendto"
        ; "recvfrom"
        ; "sendmsg"
        ; "recvmsg"
        ; "shutdown"
        ; "setsockopt"
        ; "getsockopt"
        ; "getsockname"
        ; "getpeername"
        ; "socketpair"
        ]
        syscall_name
    | Process ->
      List.mem
        ~equal:String.equal
        [ "execve"
        ; "fork"
        ; "vfork"
        ; "clone"
        ; "clone3"
        ; "exit_group"
        ; "wait4"
        ; "waitid"
        ; "kill"
        ; "getpid"
        ; "getppid"
        ; "getuid"
        ; "getgid"
        ; "geteuid"
        ; "getegid"
        ; "prctl"
        ]
        syscall_name
    | Signal ->
      List.mem
        ~equal:String.equal
        [ "rt_sigaction"; "rt_sigprocmask"; "rt_sigreturn"; "sigaltstack"; "kill" ]
        syscall_name
    | Ipc ->
      (* IPC syscalls like shmget, semget, msgget, etc. We keep a minimal set here *)
      List.mem ~equal:String.equal [] syscall_name
  ;;
end

let lookup name = Map.find known_syscalls name
